jobs:
- job: push_nuget
  displayName: Push to NuGet
  steps:
  - script: echo Hello, world!
    displayName: Run a one-line script
    steps:
    - task: DotNetCoreCLI@2
        displayName: Package Projects
        inputs:
          command: pack
          outputDir: $(Build.ArtifactStagingDirectory)